import React from 'react';

export default function DownloadCenter() {
  const assets = [
    {
      title: "Research Paper (DOCX)",
      filename: "Synzyme_Genesis_Research_Paper.docx",
      url: "/Synzyme_Genesis_Research_Paper.docx",
      size: "48 KB",
      desc: "The full, publication-ready research paper containing Abstract, Introduction, Literature Survey, Methodology, Results, and Future Works. Completely formatted for MS Word.",
      icon: "📄"
    },
    {
      title: "Jupyter Notebook (IPYNB)",
      filename: "Synzyme_Genesis_Enhanced.ipynb",
      url: "/Synzyme_Genesis_Enhanced.ipynb",
      size: "4.4 MB",
      desc: "The enhanced Python pipeline notebook featuring the actual ESM-2 token generation, AlphaFold2 validation scripts, docking configurations, and beautiful Matplotlib/Seaborn analytics plots.",
      icon: "📓"
    },
    {
      title: "Candidate Sequences (FASTA)",
      filename: "synzymes.fasta",
      url: "/synzymes.fasta",
      size: "1.2 KB",
      desc: "The complete FASTA format sequence file containing wild-type IsPETase, candidate Synzyme-001, and other highly stable mutated variants generated by the model.",
      icon: "🧬"
    }
  ];

  return (
    <section style={{ padding: '6rem 0', minHeight: '85vh', display: 'flex', alignItems: 'center' }}>
      <div className="container">
        <h2 style={{ fontSize: '3rem', textAlign: 'center', marginBottom: '1rem' }}>
          Resource <span className="gradient-text">Download Center</span>
        </h2>
        <p style={{ textAlign: 'center', color: 'var(--text-secondary)', maxWidth: '800px', margin: '0 auto 4rem auto', fontSize: '1.1rem' }}>
          Take the research and computational tools with you. Download the finalized docx paper, the complete Python code sandbox, or the generated sequence files.
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '2rem' }}>
          {assets.map((asset, idx) => (
            <div key={idx} className="glass-panel" style={{ 
              padding: '2.5rem', 
              display: 'flex', 
              flexDirection: 'column', 
              justifyContent: 'space-between',
              height: '100%' 
            }}>
              <div>
                <div style={{ fontSize: '3.5rem', marginBottom: '1.5rem' }}>{asset.icon}</div>
                <h3 style={{ color: 'var(--text-primary)', marginBottom: '0.5rem', fontSize: '1.5rem' }}>
                  {asset.title}
                </h3>
                <div style={{ fontSize: '0.8rem', color: 'var(--accent-cyan)', marginBottom: '1.5rem', fontFamily: 'monospace' }}>
                  {asset.filename} • {asset.size}
                </div>
                <p style={{ color: 'var(--text-secondary)', lineHeight: '1.6', marginBottom: '2rem', fontSize: '0.95rem' }}>
                  {asset.desc}
                </p>
              </div>
              
              <a 
                href={asset.url} 
                download={asset.filename} 
                className="btn-primary" 
                style={{ textAlign: 'center', display: 'block', width: '100%', textDecoration: 'none' }}
              >
                Download Asset
              </a>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
